---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux-demo/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: test
  targetNamespace: demo

