---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./flux-demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: demo

