---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: test
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/rnrrudvy/flux/tree/master/flux-demo

